### ISSUE TITLE
BLS Implementation

### ISSUE THREAD

**Issue by akhila-raju** [PegaSysEng/artemis#104]
### TODO
- [x] Pull over Mikuli classes from Cava
- [x] Implement serialisation and deserialisation of signatures: all SSZ round-trip tests now running.
- [x] Implement the bitwise flags on the EC points as per spec
    - [x] G2 points
    - [x] G1 points
    - [x] Rework serialisation to account for these bits
- [x] Fully handle the use of compressed coordinates in the spec (Milagro uses uncompressed which creates big complications).
- [x] Finish logic for choosing correct Y coord given the compressed X coord.
- [x] Implement hash_to_G2 method
- [x] Finish `bls_verify()`
- [x] Implement `bls_verify_multiple()` (done in #386)
- [x] Implement `bls_aggregate_pubkeys()` (done in #386)
- [x] Implement `bls_aggregate_signatures()` (done in #386)
- [x] Implement multiplication of `GTPoint`s (FP12 points)  (done in #386)
- [x] Sort out random test signature generation (they are all "randomly" the same currently)
- [x] Reinstate the commented tests
- [x] Add more thorough unit testing - in progress
- [x] Incorporate the "official" tests [Latest: the test-cases are broken and do not reflect latest updates in https://github.com/ethereum/eth2.0-specs/issues/572 WIP - see #372
- [x] Check the RANDAO and proof-of-possession code to see what methods we need in order to support these in operation
- [x] Revisit Empty Signature handling. Done in #381 
- [x] Check that g1Generator is correct per the spec.
- [x] Use the BLSPublicKey type everywhere there is a Bytes48 in the codebase (analogous to the BLSSignature type). More robust, more transparent. See #403 
- [x] A few TODOs (see #409)
